theme: jekyll-theme-minimal
title: Maëlie CHAN PENG
description: Cryptology and Computer Science student currently living in France
logo: https://media.licdn.com/dms/image/v2/D4D03AQGLKiu1UuxK8w/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1725639023794?e=1732752000&v=beta&t=qsNCVrnGojumgCBwRIlO6zgR2aBAlDAaW1tSmJWbROs
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
